set(CHARM_DIR "/u/ajain18/charm/netlrts-linux-x86_64/")
set(BASE_DIR "/u/ajain18/l6")
set(EIGEN_DIR "/sw/spack/deltas11-2023-03/apps/linux-rhel8-zen3/gcc-11.4.0/eigen-3.4.0-vqm46bt")
set(CUDA_DIR  "/path/to/CUDA/directory")
set(KOKKOS_DIR "/u/ajain18/l5/kokkos/install")

set(CHARMC "${CHARM_DIR}/bin/charmc")
set(CPU_OPTS "-c++-option -std=c++20 -O3 -march=native -DNDEBUG")
set(GPU_OPTS "-std=c++20 -O3 -march=native -DNDEBUG")
set(GPU_LINK_OPTS -O3 -language charm++ -L${KOKKOS_DIR}/lib64 -lkokkoscore -L${CUDA_DIR} -lcuda -lcudart)
set(LD_OPTS "")
set(INCS "-I${BASE_DIR}")
