# point these to absolute paths
CHARM_DIR = /home/nk/install/release/charm-mpi-smp
BASE_DIR = /home/nk/projects/LibCharmtyles/

# common options
CHARMC = $(CHARM_DIR)/bin/charmc -DUSE_ESSL_WRAPPER=0
OPTS	= -c++-option -std=c++17 -O3 -march=native -DNDEBUG
LD_OPTS =

INCS = -I$(BASE_DIR)
