# point these to absolute paths
CHARM_DIR = /home/anant/winter2024/lbp/study/charm/netlrts-linux-x86_64-smp
BASE_DIR = /home/anant/sem7/libcharm_tiles
EIGEN_DIR = /usr/include/eigen3

# common options
CHARMC = $(CHARM_DIR)/bin/charmc -DUSE_ESSL_WRAPPER=0
OPTS	= -c++-option -std=c++17 -O3 -march=native -DNDEBUG -I$(EIGEN_DIR)
LD_OPTS =

INCS = -I$(BASE_DIR)
