# point these to absolute paths
CHARM_DIR = /Users/advaittahilyani/charm
BASE_DIR = /Users/advaittahilyani/PPL/LibCharmtyles
EIGEN_DIR = /opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3

# common options
CHARMC = $(CHARM_DIR)/bin/charmc -DUSE_ESSL_WRAPPER=0
OPTS	= -c++-option -std=c++17 -g -O0 -fno-omit-frame-pointer -march=native -DNDEBUG -I$(EIGEN_DIR)
LD_OPTS= -g -O0 -fno-omit-frame-pointer

INCS = -I$(BASE_DIR)
